language: c
sudo: required
cache: apt
os: linux
dist: bionic

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install valac libgee-0.8 libgtk-3-dev python3-pip ninja-build
  - sudo pip3 install --upgrade setuptools
  - sudo pip3 install meson
  # install libbalistica
  - curl https://github.com/fusilero/libbalistica/archive/v1.1.tar.gz -o libbalistica.tar.gz -sSL
  - tar -zxvf libbalistica.tar.gz
  - rm libbalistica.tar.gz
  - cd libbalistica* && mkdir build
  - meson . build/
  - cd build && ninja
  - sudo ninja install
  - cd ../../

script:
  - mkdir build && meson . build/ && cd build
  - ninja
